export const CART_ACTION_TYPES = {
    SET_IS_CART_OPEN: "cart/SET_IS_CART_OPEN",
    SET_CART_ITEMS: "cart/SET_CART_ITEMS",
    REMOVE_ITEM: "cart/REMOVE_ITEM",
    CLEAR_ITEM: "cart/CLEAR_ITEM",
    CLEAR_CART: "cart/CLEAR_CART",
};
